# Generated by Django 4.2.16 on 2024-11-18 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_sold', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoughtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bought', models.IntegerField()),
                ('price_bought', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_bought', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_bought', to=settings.AUTH_USER_MODEL)),
                ('item_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app1.additem')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_update', models.IntegerField()),
                ('reset_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reset_description', models.TextField(max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='app1.additem')),
                ('seller_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_paid', models.IntegerField()),
                ('buyer_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to='app1.boughtitem')),
                ('item_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_requests', to='app1.boughtitem')),
            ],
        ),
    ]
